import Navbar from "@/components/Navbar";

const methodology = [
  ["01", "INTELLIGENCE COLLECTION", "Gather relevant information and establish the mission, scope, constraints, actors, and evidence base."],
  ["02", "INFORMATION ORGANIZATION", "Structure fragmented material into an operating picture while separating fact, inference, assumption, and unknown."],
  ["03", "ANALYTICAL PROCESSING", "Evaluate relationships, patterns, inconsistencies, dependencies, and competing explanations."],
  ["04", "ADVERSARIAL INTEGRATION", "Introduce independent perspectives, challenge the working theory, and actively search for failure points."],
  ["05", "STRATEGIC OUTPUT", "Synthesize what survives scrutiny into a traceable intelligence product designed for the next decision."],
];
const states=["COLLECT","STRUCTURE","ANALYZE","CHALLENGE","VERIFY","SYNTHESIZE"];

export default function SystemPage(){return <main className="sist-page-shell"><div className="sist-grid pointer-events-none fixed inset-0"/><Navbar/><section className="relative px-6 pb-24 pt-32 sm:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[1fr_430px] lg:items-end"><div><p className="text-[9px] tracking-[0.4em] text-amber-300">SIST FRAMEWORK / CONTROLLED INTELLIGENCE PIPELINE</p><h1 className="sist-metal mt-5 text-5xl font-semibold tracking-[-0.04em] md:text-7xl">THE SYSTEM<br/>IN MOTION</h1><p className="mt-7 max-w-3xl text-base leading-8 text-gray-400 md:text-lg">SIST is structured as a controlled pipeline: information enters, competing interpretations are developed, conclusions are challenged, evidence is verified, and surviving intelligence is synthesized for action.</p></div><div className="border border-amber-300/20 bg-white/[0.025] p-6"><p className="text-[9px] tracking-[0.3em] text-gray-600">LIVE ARCHITECTURE / GATED ROUTE</p><div className="mt-7 space-y-3">{["INPUT","REASONING","CHALLENGE","VERIFICATION","OUTPUT"].map((item,i)=><div key={item} className="flex items-center gap-3"><span className={`h-2 w-2 rounded-full ${i===2?"bg-red-400":i===3?"bg-emerald-400":"bg-amber-300"}`}/><span className="h-px w-6 bg-white/10"/><span className="text-[9px] tracking-[0.2em] text-gray-400">{item}</span></div>)}</div></div></div>

<div className="mt-16 overflow-hidden border border-white/10 bg-white/[0.02]"><div className="grid grid-cols-3 border-b border-white/10 bg-white/[0.025] text-[9px] tracking-[0.3em] text-gray-500 md:grid-cols-6">{states.map((state,i)=><div key={state} className="border-r border-white/10 px-4 py-4 last:border-0"><span className={i===3?"text-red-300":i===4?"text-emerald-300":"text-amber-300"}>0{i+1}</span><br/>{state}</div>)}</div><div className="relative p-6 sm:p-8"><div className="absolute left-10 right-10 top-[128px] hidden h-px bg-gradient-to-r from-amber-300/30 via-red-400/60 to-emerald-400/50 lg:block"/><div className="relative grid gap-4 md:grid-cols-5">{methodology.map(([number,title,description],index)=><article key={number} className={`sist-gate-frame relative border bg-black/80 p-6 backdrop-blur ${index===3?"border-red-400/25":index===4?"border-emerald-400/25":"border-amber-300/15"}`}><span className={`font-mono text-xs ${index===3?"text-red-300":index===4?"text-emerald-300":"text-amber-300"}`}>{number}</span><div className="mt-6 flex items-center gap-2"><span className={`h-3 w-3 rounded-full ${index===3?"bg-red-400":index===4?"bg-emerald-400":"bg-amber-300"} shadow-[0_0_14px_currentColor]`}/><span className="h-px flex-1 bg-white/10"/></div><h2 className="mt-5 text-sm font-semibold leading-6 text-gray-200">{title}</h2><p className="mt-3 text-xs leading-6 text-gray-600">{description}</p></article>)}</div></div></div>

<div className="mt-8 grid gap-5 md:grid-cols-3"><div className="border border-amber-300/20 bg-amber-300/[0.025] p-7"><p className="text-[9px] tracking-[0.3em] text-amber-300">PRIMARY ROUTE</p><p className="mt-4 text-sm leading-7 text-gray-500">Sequential reasoning moves through controlled gates before intelligence reaches output.</p></div><div className="border border-red-400/20 bg-red-400/[0.025] p-7"><p className="text-[9px] tracking-[0.3em] text-red-300">ADVERSARIAL LAYER</p><p className="mt-4 text-sm leading-7 text-gray-500">Challenge is an active control layer, not a decorative branch of the workflow.</p></div><div className="border border-emerald-400/20 bg-emerald-400/[0.025] p-7"><p className="text-[9px] tracking-[0.3em] text-emerald-300">VERIFICATION GATE</p><p className="mt-4 text-sm leading-7 text-gray-500">Critical claims are checked before the final intelligence product is released.</p></div></div></div></section></main>}
